### ISSUE TITLE
An unexpected decode results

### ISSUE THREAD

**Issue by allex** [KilledByAPixel/JSONCrush#11]
```sh
$ node -p '
var t=require("./JSONCrush.js"); 
var source=JSON.stringify({"c":"!()"})
var encode=t.JSONCrush(source);
var decode = decodeURIComponent(t.JSONUncrush(encode))
console.log({ source, encode, decode, result: source === decode })
'
```
-->

```
{
  source: '{"c":"!()"}',
  encode: "('c!''%3A%7B%7D')_",
  decode: '{"c":"":{}"}',
  result: false
}
```

**Comment by allex** [comment]
seems my problem, should `decodeURIComponent` the decoded string before uncrushing.

like this, ok.

```
$ node -p '
var t=require("./JSONCrush.js"); 
var source=JSON.stringify({"c":"!()"})
var encode=t.JSONCrush(source);
var decode = t.JSONUncrush(decodeURIComponent(encode))
console.log({ source, encode, decode, result: source === decode })
'
```

--> 

```
{
  source: '{"c":"!()"}',
  encode: "('c!''%3A%7B%7D')_",
  decode: '{"c":"!()"}',
  result: true
}
```

btw, For the principle of  I/O consistency, why not add `decodeURIComponent` in `JSONUncrush`?

please just close it.

**Comment by KilledByAPixel** [comment]
Glad you figured it out...

> btw, For the principle of I/O consistency, why not add decodeURIComponent in JSONUncrush?

It is a good question!

I wish it could work that way. The reason it can't is because searchParams.get() automatically calls decodeURIComponent on the string, and that is the most common use method. So if Uncrush also did it, then it would try to decode it a second time which could cause problems.
