### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by FlorianWendelborn** [KilledByAPixel/JSONCrush#7]
Are there any plans to publish this to NPM so people can actually use it?

**Comment by KilledByAPixel** [comment]
I would like to do that, though I think you can still use it. I am not big on the NPMs but I will try to hook that up soon for everyone.

**Comment by KilledByAPixel** [comment]
NPM exists! Someone else has already set it up.

npm install jsoncrush

Let me know if that works ok for you.

**Comment by darcyparker** [comment]
I wanted to add some clarity about why I `+1` the previous comment's confused emoji because it may not be obvious...

The npm module points to the fork https://github.com/dprothero/JSONCrush. 

If I compare the master branches: https://github.com/KilledByAPixel/JSONCrush/compare/master...dprothero:master, I can see a few obvious things:

* a light weight typescript definition (Good: not complete yet, but a start. I will probably submit a pull request in future to update it)
* `JSONCrush()` and `JSONUncrush()` are exported (This is nice for people who want to import/bundle the lib themselves)
* A lot of whitespace / reformatting. But possibly more. (I want to trust its just whitespace change, but have not verified it.)
* The fork's commits is based on https://github.com/dprothero/JSONCrush/commit/1cd1e2c3799f1313380afc27f020811233cceadf May 28, 2020 commit... and you are a few commits ahead now.  The additional commits don't feel significant enough for me to care, but it seems like it would be a lot of work to make sure the fork registered in npm and your work is synced.

It's nice that @dprothero created an npm module for the community. I can understand you may not be a big fan of npm... but having diverged forks is not great for the community.  Perhaps you and @dprothero could work out a plan to keep your repos synced or have just one official repo? As a potential user, I'd feel better if there was just one official repo that everyone is submitting their pull requests to.

BTW: JSONCrush looks great.  I have compared it to https://www.jsonurl.org/ and other related work it references. I am leaning towards yours.  I am just confused about which fork I should use.  And if I used yours, (even if it is not registered in npm), I'd want a `package.json` so that I can install it with `npm install https://github.com/KilledByAPixel/JSONCrush` and use tools like [nlf](https://github.com/iandotkelly/nlf) to create a report of every dependency's license, etc... Having atleast a `package.json` makes our lives easier and more likely to adopt JSONCrush.

**Comment by KilledByAPixel** [comment]
Darcy, thanks for the suggestion. 

It's been a while since this came up, and I have spent some time with NPM since then. I can see why this would be good, and I would like to republish on npm myself.

I have recently done some npm stuff and published zzfx (a tiny sound effect library) and added modules also so this would be a similar change.

**Comment by FlorianWendelborn** [comment]
@KilledByAPixel I think we should re-open this issue then
